import os

CONTENT_LENGTH = 'Content-Length'
CONTENT_TYPE = 'Content-Type'
X_HUB_SIGNATURE = 'X-Hub-Signature'

HOST_NAME = '0.0.0.0'
HOST_PORT = os.getenv('HOST_PORT')
LEASE_SECONDS = 864000  # 864000 seconds = 10 days = max

TWITCH_CLIENT_ID = os.getenv('TWITCH_CLIENT_ID')
TWITCH_CLIENT_SECRET = os.getenv('TWITCH_CLIENT_SECRET')
DISCORD_BOT_TOKEN = os.getenv('DISCORD_BOT_TOKEN')

COMMAND_PREFIX = "!"

SUBSCRIBE_TO_LIVE_NOTIFS_NAMES = ['stabbystabby']
ANNOUNCE_CHANNEL = 710309731234873424
