version: 2.1

orbs:
  python: circleci/python@0.2.1
  sonarcloud: sonarsource/sonarcloud@1.0.1

defaults: &defaults
  working_directory: ~/discord-bot
  docker:
    - image: circleci/python:3.8

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: python -m pytest tests
          name: Test
      - python/save-cache
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build-and-test