version: 2.1

orbs:
  python: circleci/python@0.2.1
  sonarcloud: sonarsource/sonarcloud@1.0.1

defaults: &defaults
  working_directory: ~/discord-bot
  docker:
    - image: circleci/python:3.8

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: auth-serverless-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/auth-serverless
      - restore_cache:
          keys:
            - auth-serverless-deps-{{ checksum "requirements.txt" }}
      - run:
          name: Install and activate virtual environment
          command: |
            if [ ! -d "venv" ]; then
              pip install virtualenv
              virtualenv venv
            fi
      - run:
          name: Install circle requirements
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: auth-serverless-deps-{{ checksum "requirements.txt" }}
          paths:
            - venv
  pytest:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - auth-serverless-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - auth-serverless-deps-{{ checksum "requirements.txt" }}
      - run:
          name: Run coverage tests with pytest
          command: |
            . venv/bin/activate
            coverage run -m pytest
      - run:
          name: Generate coverage report
          command: |
            . venv/bin/activate
            coverage xml -o test-coverage/coverage.xml
      - store_test_results:
          path: test-coverage
      - store_artifacts:
          path: test-coverage
      - sonarcloud/scan

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - pytest:
          requires:
            setup